AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Repository responsible for crawling INCC index data.
  INCC means "Indice Nacional de Construçao Civil" in Brazil and it tracks inflation of construct materials.

Parameters:
  BotToken:
    Type: String
    Description: Token used to send message to Telegram
  ChatId:
    Type: String
    Description: Chat id where the bot should send the message to

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CrawlerINCCFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src
      Handler: main.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          BOT_TOKEN: !Ref BotToken
          CHAT_ID: !Ref ChatId
      Events:
        CrawlerINCC:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CrawlerINCCApi:
    Description: "API Gateway endpoint URL for the function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/incc-crawler/"
  CrawlerINCCFunction:
    Description: "Crawler Lambda Function ARN"
    Value: !GetAtt CrawlerINCCFunction.Arn
  CrawlerINCCFunctionIamRole:
    Description: "Implicit IAM Role created for INCC Crawler function"
    Value: !GetAtt CrawlerINCCFunctionRole.Arn
